[package]
name = "wsldhost"
version = "0.1.0"
authors = ["Gary Guo <gary@garyguo.net>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
tokio = { version = "1.7", features = ["net", "rt", "macros", "io-util", "time", "process", "fs"] }
async-io = "1"
once_cell = "1"
winapi = { version = "0.3", features = ["wincon", "libloaderapi", "combaseapi"] }
winreg = "0.10"
widestring = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
uuid = { version = "0.8", features = ["serde"] }
clap = { version = "3.0", default-features = false, features = ["std", "derive"] }
